"""Seed templates for the 14 v4.1 bot products. Single source of truth for the API."""
from __future__ import annotations

COMPILER_VERSION = "bot-spec-compiler-v4.1.0"

TEMPLATES = [
    {
        "template_id": "tpl_spot_grid",
        "bot_type": "spot_grid",
        "display_name": "Spot Grid Lab",
        "description": "Buy/sell grid across a range. Sideways markets. Strict-penetration fills; cycle counts reported as a range.",
        "category": "grid",
        "risk_class": "MODERATE",
        "default_params": {"symbol": "BTCUSDT", "lower_price": "60000", "upper_price": "70000", "grid_count": 10, "grid_spacing": "arithmetic", "investment_quote": "1000"},
        "eligibility_hint": "APPROXIMATE_FILLS",
    },
    {
        "template_id": "tpl_futures_grid",
        "bot_type": "futures_grid",
        "display_name": "Futures Grid Lab",
        "description": "Perp grid (neutral/long/short) with funding, mark, liquidation distance.",
        "category": "grid",
        "risk_class": "HIGH",
        "default_params": {"symbol": "BTCUSDT", "lower_price": "60000", "upper_price": "70000", "grid_count": 10, "direction": "neutral", "leverage": 1, "investment_quote": "1000"},
        "eligibility_hint": "APPROXIMATE_FILLS",
    },
    {
        "template_id": "tpl_dca",
        "bot_type": "dca",
        "display_name": "DCA / Auto-Invest Lab",
        "description": "Recurring spot purchases on a schedule. Accumulation, not trading.",
        "category": "dca",
        "risk_class": "LOW",
        "default_params": {"symbol": "BTCUSDT", "investment_quote_per_order": "100", "frequency_bars": 96, "max_total_investment": "1000"},
        "eligibility_hint": "HISTORICAL_FACTOR_OK",
    },
    {
        "template_id": "tpl_futures_dca",
        "bot_type": "futures_dca",
        "display_name": "Futures DCA Lab",
        "description": "Structured averaging into a leveraged position with explicit TP cycles.",
        "category": "dca",
        "risk_class": "HIGH",
        "default_params": {"symbol": "BTCUSDT", "direction": "long", "base_order_margin": "100", "dca_order_margin": "100", "price_deviation_fraction": "0.03", "max_dca_orders": 5, "take_profit_fraction": "0.01"},
        "eligibility_hint": "HISTORICAL_FACTOR_OK",
    },
    {
        "template_id": "tpl_futures_martingale",
        "bot_type": "futures_martingale",
        "display_name": "Futures Martingale Lab",
        "description": "Size-up recovery strategy on adverse moves. HIGH-RISK. Hard stop-loss + ruin simulator required.",
        "category": "recovery",
        "risk_class": "VERY_HIGH",
        "default_params": {"symbol": "BTCUSDT", "direction": "long", "base_order_margin": "100", "safety_order_margin": "100", "safety_order_multiplier": "1.5", "price_deviation_fraction": "0.02", "deviation_multiplier": "1.0", "max_safety_orders": 5, "take_profit_fraction_from_avg_entry": "0.01", "hard_stop_loss_fraction": "0.30", "leverage": 1},
        "eligibility_hint": "HISTORICAL_FACTOR_OK",
    },
    {
        "template_id": "tpl_futures_combo",
        "bot_type": "futures_combo",
        "display_name": "Futures Combo Lab",
        "description": "Multi-symbol long/short futures portfolio. Weights as fraction of gross notional.",
        "category": "portfolio",
        "risk_class": "HIGH",
        "default_params": {"total_investment": "10000", "rebalance": {"mode": "threshold_or_time", "threshold_fraction": "0.05", "interval_hours": 24}, "symbols": [{"symbol": "BTCUSDT", "side": "long", "target_weight_fraction": "0.5", "leverage": 1}, {"symbol": "ETHUSDT", "side": "short", "target_weight_fraction": "0.5", "leverage": 1}]},
        "eligibility_hint": "HISTORICAL_FACTOR_OK",
    },
    {
        "template_id": "tpl_rebalancer",
        "bot_type": "rebalancer",
        "display_name": "Rebalancing Lab",
        "description": "Index/sector basket rebalancing. Gross-notional weight rule.",
        "category": "portfolio",
        "risk_class": "MODERATE",
        "default_params": {"total_investment": "10000", "rebalance": {"mode": "threshold_or_time", "threshold_fraction": "0.05", "interval_hours": 168}, "symbols": [{"symbol": "BTCUSDT", "side": "long", "target_weight_fraction": "0.6", "leverage": 1}, {"symbol": "ETHUSDT", "side": "long", "target_weight_fraction": "0.4", "leverage": 1}]},
        "eligibility_hint": "HISTORICAL_FACTOR_OK",
    },
    {
        "template_id": "tpl_funding_arbitrage",
        "bot_type": "funding_arbitrage",
        "display_name": "Funding Arbitrage Lab",
        "description": "Delta-neutral funding carry. Paper-only. synthetic_spot carries its declared cost.",
        "category": "carry",
        "risk_class": "MODERATE",
        "default_params": {"perp_symbol": "BTCUSDT", "spot_symbol": "BTCUSDT", "synthetic_spot": {"mode": "held", "carrying_cost_bps_per_day": "0"}, "entry": {"min_funding_rate": "0.0002"}, "exit": {"funding_rate_below": "0.00005", "max_holding_hours": 240}, "hedge_rebalance": {"threshold_delta_fraction": "0.05"}},
        "eligibility_hint": "PAPER_ONLY_LIVE",
    },
    {
        "template_id": "tpl_twap",
        "bot_type": "twap",
        "display_name": "TWAP Execution Lab",
        "description": "Equal-slice time-weighted execution. Verified shortfall requires L2.",
        "category": "execution",
        "risk_class": "LOW",
        "default_params": {"symbol": "BTCUSDT", "side": "buy", "total_qty": "1.0", "slice_count": 10, "order_style": "market"},
        "eligibility_hint": "APPROXIMATE_FILLS",
    },
    {
        "template_id": "tpl_vp_pov",
        "bot_type": "vp_pov",
        "display_name": "VP/POV Execution Lab",
        "description": "Participation-rate execution. Sizes off PRIOR bar volume (no current-bar look-ahead).",
        "category": "execution",
        "risk_class": "LOW",
        "default_params": {"symbol": "BTCUSDT", "side": "buy", "target_qty": "10", "participation_rate_fraction": "0.05", "max_participation_rate_fraction": "0.10", "min_slice_qty": "0.001", "max_slice_qty": "1.0"},
        "eligibility_hint": "APPROXIMATE_FILLS",
    },
    {
        "template_id": "tpl_chase_limit",
        "bot_type": "chase_limit",
        "display_name": "Chase Limit Execution Lab",
        "description": "Limit tracking best bid/ask. Requires L1/L2 for realistic simulation.",
        "category": "execution",
        "risk_class": "LOW",
        "default_params": {"symbol": "BTCUSDT", "side": "buy", "qty": "1.0", "chase_reference": "bid1", "offset_type": "bps", "offset_value": "1", "max_chase_distance_bps": "20", "post_only": True, "timeout_seconds": 600},
        "eligibility_hint": "APPROXIMATE_FILLS",
    },
    {
        "template_id": "tpl_iceberg",
        "bot_type": "iceberg",
        "display_name": "Iceberg Execution Lab",
        "description": "Scheduler that exposes only visible_qty at a time. Fill ordering verified only under L2.",
        "category": "execution",
        "risk_class": "LOW",
        "default_params": {"symbol": "BTCUSDT", "side": "buy", "total_qty": "10", "visible_qty": "1", "price_limit": "65000", "order_style": "limit"},
        "eligibility_hint": "APPROXIMATE_FILLS",
    },
    {
        "template_id": "tpl_scaled_order",
        "bot_type": "scaled_order",
        "display_name": "Scaled Order Execution Lab",
        "description": "One-shot split into N limits across a range. No auto-replacement.",
        "category": "execution",
        "risk_class": "LOW",
        "default_params": {"symbol": "BTCUSDT", "side": "buy", "total_qty": "10", "lower_price": "60000", "upper_price": "70000", "order_count": 5, "distribution": "equal", "post_only": True},
        "eligibility_hint": "APPROXIMATE_FILLS",
    },
    {
        "template_id": "tpl_cross_asset_allocator",
        "bot_type": "cross_asset_allocator",
        "display_name": "Cross-Asset Allocator (Crypto + xStocks)",
        "description": "One USDT book that rotates between crypto and tokenized US equities (xStocks), 24/7. Static / momentum / regime-switch. Equity sleeve is long-only, unleveraged, RTH-aware.",
        "category": "portfolio",
        "risk_class": "MODERATE",
        "default_params": {
            "mode": "regime_switch",
            "total_investment": "100000",
            "lookback_bars": 20,
            "top_n": 3,
            "pause_equity_off_hours": False,
            "rebalance": {"mode": "threshold_or_time", "threshold_fraction": "0.05", "interval_hours": 24},
            "symbols": [
                {"symbol": "BTCUSDT", "asset_class": "crypto", "side": "long", "target_weight_fraction": "0.34", "leverage": 1, "sleeve": "risk_on"},
                {"symbol": "ETHUSDT", "asset_class": "crypto", "side": "long", "target_weight_fraction": "0.16", "leverage": 1, "sleeve": "risk_on"},
                {"symbol": "NVDAXUSDT", "asset_class": "equity", "side": "long", "target_weight_fraction": "0.25", "leverage": 1, "sleeve": "risk_off"},
                {"symbol": "GOOGLXUSDT", "asset_class": "equity", "side": "long", "target_weight_fraction": "0.25", "leverage": 1, "sleeve": "risk_off"}
            ]
        },
        "eligibility_hint": "HISTORICAL_FACTOR_OK",
    },
    {
        "template_id": "tpl_position_snowball",
        "bot_type": "position_snowball",
        "display_name": "Position Snowball Lab",
        "description": "Add to winning futures position. ROI trigger and liquidation evaluated off SAME per-bar mark.",
        "category": "compounding",
        "risk_class": "VERY_HIGH",
        "default_params": {"symbol": "BTCUSDT", "direction": "long", "initial_margin": "100", "leverage": 1, "add_trigger_roi_fraction": "0.02", "profit_reinvestment_fraction": "0.5", "max_adds": 5, "take_profit_roi_fraction": "0.10", "stop_loss_roi_fraction": "0.10"},
        "eligibility_hint": "HISTORICAL_FACTOR_OK",
    },
]


def template_by_type(bot_type: str) -> dict | None:
    for t in TEMPLATES:
        if t["bot_type"] == bot_type:
            return t
    return None
