import type { CatalogEntry } from "./types.js";

// The 15 Bot OS products (LAB_REFERENCE §8.1–8.6). A BotSpec is
// {bot_type, name, symbols[], params, risk, accounting}. Templates are seed
// defaults only — params are fully custom.

export const BOTS: CatalogEntry[] = [
  // ---- Grid family (§8.1) ----
  {
    id: "spot_grid",
    title: "Spot Grid",
    category: "grid",
    riskClass: "MODERATE",
    summary: "Posts a buy/sell ladder across [lower_price, upper_price]; on a fill, posts the counter order one level away.",
    params: [
      { name: "lower_price", type: "decimal", required: true, unit: "price", description: "Bottom of the grid.", relatedErrorCodes: ["GRID_RANGE_INVALID", "GRID_LOWER_GTE_UPPER"] },
      { name: "upper_price", type: "decimal", required: true, unit: "price", description: "Top of the grid.", relatedErrorCodes: ["GRID_RANGE_INVALID"] },
      { name: "grid_count", type: "int", default: 10, min: 2, description: "Number of grid levels.", relatedErrorCodes: ["GRID_COUNT_TOO_LOW"] },
      { name: "grid_spacing", type: "enum", default: "arithmetic", enum: ["arithmetic", "geometric"], description: "Level distribution." },
      { name: "investment_quote", type: "decimal", unit: "USDT", description: "Total quote to deploy (auto-sizes per level)." },
      { name: "qty_per_level", type: "decimal", default: 0, unit: "qty", description: "0 = auto (investment/grid_count/ref_price)." },
    ],
  },
  {
    id: "futures_grid",
    title: "Futures Grid",
    category: "grid",
    riskClass: "HIGH",
    summary: "spot_grid on futures: direction filter, leverage, decisions on mark price. Requires funding coverage for a verified run.",
    dataRequirements: ["funding_rows", "risk_tiers (if leverage>1)"],
    params: [
      { name: "lower_price", type: "decimal", required: true, unit: "price", description: "Bottom of the grid." },
      { name: "upper_price", type: "decimal", required: true, unit: "price", description: "Top of the grid." },
      { name: "grid_count", type: "int", default: 10, min: 2, description: "Number of levels." },
      { name: "grid_spacing", type: "enum", default: "arithmetic", enum: ["arithmetic", "geometric"], description: "Level distribution." },
      { name: "direction", type: "enum", default: "neutral", enum: ["neutral", "long", "short"], description: "Which side(s) of levels are active.", relatedErrorCodes: ["DIRECTION_INVALID"] },
      { name: "leverage", type: "decimal", default: 1, unit: "x(leverage)", description: ">1 requires risk tiers.", relatedErrorCodes: ["MARGIN_TIERS_MISSING", "FUTURES_LEVERAGE_WITHOUT_MARGIN_TIERS"] },
      { name: "mmr_fraction", type: "decimal", default: 0.005, unit: "fraction", description: "Maintenance-margin rate." },
    ],
  },
  // ---- DCA family (§8.2) ----
  {
    id: "dca",
    title: "DCA (spot)",
    category: "dca",
    riskClass: "LOW",
    summary: "Buys investment/price every frequency_bars; skips on price filter or max-investment reached.",
    params: [
      { name: "investment_quote_per_order", type: "decimal", default: 100, unit: "USDT", description: "Spend per buy." },
      { name: "frequency_bars", type: "int", default: 1, unit: "bars", description: "Buy cadence." },
      { name: "max_total_investment", type: "decimal", default: 1000, unit: "USDT", description: "Stop buying past this cumulative spend." },
      { name: "price_filter_max", type: "decimal", default: 0, unit: "price", description: "0 = no filter; else skip buys above this price." },
    ],
  },
  {
    id: "futures_dca",
    title: "Futures DCA",
    category: "dca",
    riskClass: "HIGH",
    summary: "Opens a base + TP, then adds escalating safety orders as price deviates, re-averaging entry and re-pricing TP.",
    dataRequirements: ["risk_tiers (if leverage>1)"],
    params: [
      { name: "direction", type: "enum", default: "long", enum: ["long", "short"], description: "Position direction." },
      { name: "base_order_margin", type: "decimal", required: true, unit: "USDT", description: "Margin for the base order." },
      { name: "dca_order_margin", type: "decimal", required: true, unit: "USDT", description: "Margin for the first safety order." },
      { name: "price_deviation_fraction", type: "decimal", default: 0.03, unit: "fraction", description: "Base deviation that triggers the next safety order." },
      { name: "deviation_multiplier", type: "decimal", default: 1.0, description: "Geometric growth of the deviation trigger." },
      { name: "dca_order_multiplier", type: "decimal", default: 1.0, description: "Geometric growth of safety-order size." },
      { name: "max_dca_orders", type: "int", default: 5, description: "Cap on safety orders." },
      { name: "take_profit_fraction", type: "decimal", default: 0.01, unit: "fraction", description: "TP distance from average entry." },
    ],
  },
  {
    id: "futures_martingale",
    title: "Futures Martingale",
    category: "dca",
    riskClass: "VERY_HIGH",
    summary: "futures_dca with safety_order_multiplier>1 and a REQUIRED hard stop. Validator runs a ruin simulator.",
    eligibilityNotes: ["Cockpit hard-blocks martingale without a stop loss."],
    params: [
      { name: "direction", type: "enum", default: "long", enum: ["long", "short"], description: "Position direction." },
      { name: "base_order_margin", type: "decimal", required: true, unit: "USDT", description: "Base order margin." },
      { name: "dca_order_margin", type: "decimal", required: true, unit: "USDT", description: "First safety order margin." },
      { name: "safety_order_multiplier", type: "decimal", default: 1.5, min: 1.0, description: "Geometric size growth (>1).", relatedErrorCodes: ["RUIN_MARGIN_EXCEEDS_CAPITAL"] },
      { name: "hard_stop_loss_fraction", type: "decimal", required: true, min: 0, description: "REQUIRED > 0.", relatedErrorCodes: ["HARD_STOP_REQUIRED", "MARTINGALE_WITHOUT_STOP_LOSS"] },
      { name: "max_dca_orders", type: "int", default: 5, description: "Cap on safety orders (drives the ruin ladder)." },
      { name: "price_deviation_fraction", type: "decimal", default: 0.03, unit: "fraction", description: "Trigger deviation." },
    ],
  },
  // ---- Portfolio family (§8.3) ----
  {
    id: "futures_combo",
    title: "Futures Combo",
    category: "portfolio",
    riskClass: "HIGH",
    summary: "Opens each leg at total_investment*|weight|*leverage/mark; rebalances a leg past threshold. Gross weights must sum to 1.0.",
    params: [
      { name: "total_investment", type: "decimal", required: true, unit: "USDT", description: "Total notional budget." },
      { name: "symbols", type: "array", required: true, description: "Legs: [{symbol, side, target_weight_fraction, leverage}]. Σ|weight|==1.0.", relatedErrorCodes: ["COMBO_GROSS_WEIGHTS_NOT_ONE", "GROSS_WEIGHT_SUM_INVALID"] },
      { name: "rebalance.threshold_fraction", type: "decimal", default: 0.05, unit: "fraction", description: "Drift before a leg rebalances." },
    ],
  },
  {
    id: "rebalancer",
    title: "Rebalancer",
    category: "portfolio",
    riskClass: "MODERATE",
    summary: "futures_combo + spot_mode (blocks sells when position<=0).",
    params: [
      { name: "total_investment", type: "decimal", required: true, unit: "USDT", description: "Total budget." },
      { name: "symbols", type: "array", required: true, description: "Legs [{symbol, side, target_weight_fraction, leverage}]." },
      { name: "spot_mode", type: "bool", default: false, description: "Block sells when position<=0 (spot semantics)." },
      { name: "rebalance.threshold_fraction", type: "decimal", default: 0.05, unit: "fraction", description: "Rebalance drift threshold." },
    ],
  },
  {
    id: "cross_asset_allocator",
    title: "Cross-Asset Allocator",
    category: "portfolio",
    riskClass: "MODERATE",
    summary: "Mixes crypto + xStocks. Equity legs forced spot/long/lev-1 and skipped off-RTH. 300k USDT/token cap.",
    params: [
      { name: "mode", type: "enum", default: "static", enum: ["static", "momentum", "regime_switch"], description: "Weighting mode." },
      { name: "total_investment", type: "decimal", required: true, unit: "USDT", description: "Total budget." },
      { name: "lookback_bars", type: "int", default: 20, unit: "bars", description: "Trailing window for momentum/regime." },
      { name: "top_n", type: "int", default: 3, description: "How many legs to hold in momentum mode." },
      { name: "pause_equity_off_hours", type: "bool", default: true, description: "Hold equity legs flat off-RTH." },
      { name: "symbols", type: "array", required: true, description: "Legs [{symbol, asset_class, side, target_weight_fraction, leverage, sleeve}].", relatedErrorCodes: ["XSTOCK_SHORT_NOT_ALLOWED", "XSTOCK_LEVERAGE_NOT_ALLOWED"] },
    ],
  },
  // ---- Carry (§8.4) ----
  {
    id: "funding_arbitrage",
    title: "Funding Arbitrage",
    category: "carry",
    riskClass: "MODERATE",
    summary: "Delta-neutral: positive funding -> long spot + short perp (collect funding). PAPER-ONLY for live. Requires funding coverage.",
    dataRequirements: ["funding_rows"],
    params: [
      { name: "spot_symbol", type: "string", required: true, description: "Spot leg symbol." },
      { name: "perp_symbol", type: "string", required: true, description: "Perp leg symbol." },
      { name: "base_notional", type: "decimal", default: 1000, unit: "USDT", description: "Per-leg notional." },
      { name: "entry_min_funding_rate", type: "decimal", default: 0.0001, unit: "fraction", description: "Min funding to enter." },
      { name: "hedge_ratio", type: "decimal", default: 1.0, description: "Perp/spot hedge ratio." },
      { name: "allow_reverse_carry", type: "bool", default: false, description: "Allow entering on negative funding." },
    ],
  },
  // ---- Execution family (§8.5, all APPROXIMATE_FILLS) ----
  {
    id: "twap",
    title: "TWAP (bot)",
    category: "execution",
    riskClass: "LOW",
    summary: "One equal market slice per bar.",
    eligibilityNotes: ["APPROXIMATE_FILLS — needs recorded L1/L2 for a verified tier."],
    params: [
      { name: "total_qty", type: "decimal", required: true, unit: "qty", description: "Total to execute." },
      { name: "side", type: "enum", default: "buy", enum: ["buy", "sell"], description: "Direction." },
      { name: "slice_count", type: "int", default: 10, description: "Number of slices." },
    ],
  },
  {
    id: "vp_pov",
    title: "Volume/POV Executor",
    category: "execution",
    riskClass: "LOW",
    summary: "Child = clamp(prior_bar_volume*rate, min, max), capped by remaining; pauses on a volume spike.",
    dataRequirements: ["bars with volume"],
    eligibilityNotes: ["APPROXIMATE_FILLS; needs prior-bar volume (VP_MISSING_VOLUME)."],
    params: [
      { name: "target_qty", type: "decimal", required: true, unit: "qty", description: "Total to execute." },
      { name: "participation_rate_fraction", type: "decimal", default: 0.05, unit: "fraction", description: "Target % of bar volume." },
      { name: "max_participation_rate_fraction", type: "decimal", default: 0.10, unit: "fraction", description: "Hard cap on participation." },
      { name: "min_slice_qty", type: "decimal", unit: "qty", description: "Lower clamp on child size." },
      { name: "max_slice_qty", type: "decimal", unit: "qty", description: "Upper clamp on child size." },
      { name: "anti_spike.volume_zscore_above", type: "decimal", default: 999, description: "Pause when volume z-score exceeds this." },
    ],
  },
  {
    id: "chase_limit",
    title: "Chase Limit",
    category: "execution",
    riskClass: "LOW",
    summary: "Re-prices a limit toward the mark each bar, capped at start_ref ± max_chase_distance; on timeout cancels or crosses.",
    eligibilityNotes: ["APPROXIMATE_FILLS without recorded L1/L2."],
    params: [
      { name: "qty", type: "decimal", required: true, unit: "qty", description: "Quantity to execute." },
      { name: "offset_bps", type: "decimal", required: true, unit: "bps", description: "Initial passive offset from mark." },
      { name: "max_chase_distance_bps", type: "decimal", default: 30, unit: "bps", description: "Cap on how far the chase moves." },
      { name: "timeout_bars", type: "int", default: 10, unit: "bars", description: "Bars before fallback fires." },
      { name: "fallback_policy", type: "enum", default: "cancel", enum: ["cancel", "market"], description: "On timeout: cancel or cross." },
    ],
  },
  {
    id: "iceberg",
    title: "Iceberg",
    category: "execution",
    riskClass: "LOW",
    summary: "Exposes only visible_qty; on fill posts the next slice (market if price_limit=0).",
    eligibilityNotes: ["APPROXIMATE_FILLS without recorded L1/L2."],
    params: [
      { name: "total_qty", type: "decimal", required: true, unit: "qty", description: "Total to execute." },
      { name: "visible_qty", type: "decimal", required: true, unit: "qty", description: "Displayed slice size." },
      { name: "price_limit", type: "decimal", default: 0, unit: "price", description: "0 = market slices; else limit price." },
    ],
  },
  {
    id: "scaled_order",
    title: "Scaled Order",
    category: "execution",
    riskClass: "LOW",
    summary: "One-shot ladder across [lower_price, upper_price] with weighted sizes.",
    eligibilityNotes: ["APPROXIMATE_FILLS without recorded L1/L2."],
    params: [
      { name: "total_qty", type: "decimal", required: true, unit: "qty", description: "Total to ladder." },
      { name: "lower_price", type: "decimal", required: true, unit: "price", description: "Bottom of the ladder." },
      { name: "upper_price", type: "decimal", required: true, unit: "price", description: "Top of the ladder." },
      { name: "order_count", type: "int", default: 5, description: "Number of rungs." },
      { name: "distribution", type: "enum", default: "equal", enum: ["equal", "increasing", "decreasing"], description: "Size weighting across rungs." },
    ],
  },
  // ---- Compounding (§8.6) ----
  {
    id: "position_snowball",
    title: "Position Snowball",
    category: "compounding",
    riskClass: "VERY_HIGH",
    summary: "Adds to a winner when ROI crosses the trigger (reinvesting profit) only if projected post-add liquidation distance stays above the floor.",
    params: [
      { name: "direction", type: "enum", default: "long", enum: ["long", "short"], description: "Position direction." },
      { name: "initial_margin", type: "decimal", required: true, unit: "USDT", description: "Starting margin." },
      { name: "add_trigger_roi_fraction", type: "decimal", default: 0.02, unit: "fraction", description: "ROI that triggers an add." },
      { name: "profit_reinvestment_fraction", type: "decimal", default: 0.5, unit: "fraction", description: "Share of position reinvested per add." },
      { name: "max_adds", type: "int", default: 5, description: "Cap on adds." },
      { name: "cooldown_bars_between_adds", type: "int", default: 1, unit: "bars", description: "Min bars between adds." },
      { name: "liquidation_distance_floor_fraction", type: "decimal", default: 0.03, unit: "fraction", description: "Reject an add if projected liq distance falls below this.", relatedErrorCodes: ["RISK_REJECTION:LIQUIDATION_FLOOR_BREACH"] },
      { name: "take_profit_roi_fraction", type: "decimal", default: 0.10, unit: "fraction", description: "Exit at this ROI." },
      { name: "stop_loss_roi_fraction", type: "decimal", default: 0.03, unit: "fraction", description: "Exit at this loss." },
    ],
  },
];
